export {default as Home} from './Home'
export {default as Detail} from './Detail'
export {default as Schedule} from './Detail/Schedule'
export {default as WebView} from './WebView'
export {default as ViewAll} from './ViewAll'
export {default as Map} from './Detail/Map'