export default {
    sflashscreen: "SflashScreen",
    login: "Login",
    loginapp: "LoginApp",
    registration: "RegisTration",
    home: "Home",
    detail: "Detail",
    listmytour: "ListMytour",
    createtour: "CreateTour",
    listnotifycation: "ListNotifycation",
    homesetting: "HomeSetting",
    schedule: "Schedule",
    setting: "Setting",
    profile: "Profile",
    editprofile: "EditProfile",
    changepass: "ChangePass",
    webview: "WebView",
    viewall: "ViewAll",
    map: "Map",
    forgotpassword: 'ForgotPassWord',
    createdetail: 'CreateDetail',
}